- hosts: windows                   
  gather_facts: no
  collections:
    - ansible.windows            

  tasks:
    - name: Install found updates
      ansible.windows.win_updates:  
        category_names: []   
        state: installed               
      register: update_install_result
      
    - name: Show full update install result
      debug:
        var: update_install_result
