- hosts: windows                   
  gather_facts: no
  collections:
    - ansible.windows            

  tasks:
    - name: Install a specific update by KB number
      ansible.windows.win_updates:
        category_names: []      
        state: installed       
        kb_numbers:
          - 890830            
      register: update_install_result
