---
- name: Check for available patches on Lenovo Windows servers
  hosts: windows                   
  gather_facts: no
  collections:
    - ansible.windows            

  tasks:
    - name: test connectivity
      win_ping:                  

    - name: List available updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates        
        state: searched           
      register: available_updates
      
    - name: Show list of updates
      debug:
        var: available_updates.found_updates
        
    - name: Show full update check result
      debug:
        var: available_updates
