---
- name: Check for available patches on Lenovo Windows servers
  hosts: win-srv01
  gather_facts: no
  tasks:
    - name: List available updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        state: searched
      register: available_updates

    - name: Show list of updates
      debug:
        var: available_updates.found_updates
