- hosts: win_srvs                   
  gather_facts: no
  collections:
    - ansible.windows            

  tasks:
    - name: Download found updates
      ansible.windows.win_updates:  
        category_names:
          - SecurityUpdates
        accept_list:
          - KB5062572
        state: downloaded
                    
      register: update_download_result
      
    - name: Show full update install result
      debug:
        var: update_download_result  
        

